package assets

// The units as the game draws them: 24x24 pixel figures, one string per
// row, one character per pixel, keyed like Cast ("hero_<id>",
// "unit_<id>"). They are drawn for this game's world — operators in a
// dark-fibre dystopia, not fantasy — and replace the Tiny Dungeon
// placeholders in the graphical client. The style: near-black silhouettes
// with almost no interior detail, a rim of light on the upper edges, one
// strong prop each, and one or two glowing pixels for eyes and lights. A terminal can draw the same
// grids with half blocks, two pixels to a cell.
//
// Palette characters are listed in Palette; "T" and "t" are the team's
// colour and its shade, filled in per side when drawn (visors, armbands,
// lights), so a figure says whose it is without an outline.

// UnitSize is the width and height of every figure, in pixels.
const UnitSize = 24

// Palette maps a pixel character to its colour ("" = transparent; T and
// t are filled with the team colour by whoever draws).
var Palette = map[byte]string{
	'.': "",
	'K': "#0b0e12", // outline
	'd': "#161b21", // fold, seam
	'D': "#46525f", // rim light
	'B': "#3a4b5e", // coat
	'b': "#26323f", // coat shadow
	'G': "#4f5b66", // armour
	'L': "#8593a0", // metal
	'W': "#d0d9e0", // highlight, medic white
	'S': "#b88c6e", // skin
	's': "#8a6450", // skin shadow
	'O': "#6b4a2f", // leather
	'Y': "#c9a13a", // hazard amber
	'R': "#b23a30", // red
	'T': "team",
	't': "team-shade",
}

// Floating figures hover: they bob over a shadow that stays put, instead
// of breathing on their feet.
var Floating = map[string]bool{"hero_nul": true, "unit_drone": true}

// Units holds every figure.
var Units = map[string][]string{
	// HASK, breaker: a horned brute, all shoulders and fists.
	"hero_hask": {
		"........................",
		"........................",
		"........................",
		".........K......K.......",
		".........KK....KK.......",
		"..........KKKKKK........",
		".........KDDDDDDK.......",
		".........KKKKKKKK.......",
		".........KKTTKTTK.......",
		"..........KKKKKK........",
		".......KKKKKKKKKKKK.....",
		".....KKDDKKKKKKKKDDKK...",
		"....KDDKKKKKKKKKKKKDDK..",
		"....KDKKKKKKKKKKKKKKDK..",
		"...KKKKKKKKKKKKKKKKKKKK.",
		"...KKKKKKKKKdKKKKKKKKKK.",
		"...KKKKKKKKKdKKKKKKKKKK.",
		"...KKKK.KKKKKKKKKK.KKKK.",
		"...KKK..KKKKKKKKKK..KKK.",
		"...KDD..KKKKKKKKKK..DDK.",
		"....KK..KKKKKKKKKK..KK..",
		"........KKKKK.KKKK......",
		".......KKKKK..KKKKK.....",
		".......KKKK....KKKK.....",
	},
	// WREN, marksman: a wide hat, a long rifle.
	"hero_wren": {
		"........................",
		"........................",
		"........................",
		"........................",
		"..........DD............",
		".........DKKD...........",
		"........DKKKKD..........",
		"......DDKKKKKKDD........",
		"....DDDDDDDDDDDDDD......",
		".......KKKKKKKK.........",
		".......KTTKKTTK.........",
		".......KKKKKKKK.........",
		"......KKKKKKKKKK........",
		".....KDKKKKKKKKKK.......",
		".....KKKKKKKKKKKKK......",
		"....KKKKKKKKKKKKKKDDDDDD",
		"....KKKKKKKKKKKKKKKKKKK.",
		"....KDKKKKKKKKKKKK......",
		".....KKKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKK........",
		"......KKK....KKK........",
		".....KKKK....KKKK.......",
		"........................",
	},
	// NUL, operator: a floating cloak under a crown of antennas.
	"hero_nul": {
		"........................",
		"........................",
		"........................",
		"...........K............",
		"..........KDK...........",
		"...........K............",
		"........K..K..K.........",
		"........KK.K.KK.........",
		".........KKKKK..........",
		"........KKKKKKK.........",
		".......KDKKKKKKK........",
		".......KKTKKKTKK........",
		".......KKKKKKKKK........",
		"......KDKKKKKKKKK.......",
		".....KDKKKKKKKKKKK......",
		"....KDKKKKKTKKKKKKK.....",
		"....KKKKKKKKKKKKKKK.....",
		"...KDKKKKKKKKKKKKKKK....",
		"...KKKKKKKKKKKKKKKKK....",
		"...KKKKKKKKKKKKKKKKKK...",
		"..KKKK.KKKKK.KKKKKKKK...",
		"..KK....KK.....KK...K...",
		"........................",
		"........dddddddd........",
	},
	// MOTT, signaler: a mast with a lit orb.
	"hero_mott": {
		"........................",
		"........................",
		"........................",
		"........................",
		"...............tTTt.....",
		"..............tTWWTt....",
		"..............tTWWTt....",
		"...............tTTt.....",
		"................KK......",
		"...............KK.......",
		".......KKKKKK.KK........",
		"......KDDDDDDKK.........",
		"......KKKKKKKKK.........",
		"......KKTKKTKKK.........",
		"......KKKKKKKKK.........",
		".....KKKKKKKKKKK........",
		"....KDKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		"....KDKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		".....KKKKKKKKKKK........",
		"......KKK...KKK.........",
		".....KKKK...KKKK........",
		"........................",
	},
	// TALLY, summoner: goggles, and a drone at the shoulder.
	"hero_tally": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		".................KKK....",
		"................KDTDK...",
		".......KKKKK....KKKKK...",
		"......KDDDDDK....K.K....",
		"......KTTKTTK...........",
		"......KKKKKKK...........",
		".......KKKKK............",
		".....KKKKKKKKK..........",
		"....KDKKKKKKKKK.........",
		"....KKKKKKKKKKKK........",
		"....KKKKKKKKKKKDK.......",
		"....KDKKKKKKKKKKDK......",
		".....KKKKKKKKKK..KK.....",
		".....KKKKKKKKKK.........",
		"......KKK..KKK..........",
		".....KKKK..KKKK.........",
		"........................",
	},
	// Lineman: a hard hat and a coil of cable.
	"unit_lineman": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		".........DDDDDD.........",
		"........DKKKKKKD........",
		".......DDDDDDDDDD.......",
		"........KKKKKKKK........",
		"........KKTKKTKK........",
		"........KKKKKKKK..DDD...",
		".......KKKKKKKKKKD...D..",
		"......KDKKKKKKKKKKD.D...",
		"......KKKKKKKKKKKKKD....",
		"......KDKKKKKKKKKKKK....",
		"......KKKKKKKKKKKKKK....",
		".......KKKKKKKKKKK......",
		".......KKK....KKK.......",
		"......KKKK....KKKK......",
	},
	// Ranged: a visor, an aerial, a rifle.
	"unit_ranged": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........T............",
		"...........K............",
		".........KKKKKK.........",
		"........KDDDDDDK........",
		"........KKKKKKKK........",
		"........KTTTTTTK........",
		"........KKKKKKKK........",
		".......KKKKKKKKKK.......",
		"......KDKKKKKKKKKK......",
		"......KKKKKKKKKKKKKKKKKK",
		"......KDKKKKKKKKKKDDDDK.",
		"......KKKKKKKKKKKK......",
		".......KKKKKKKKKK.......",
		".......KKK....KKK.......",
		"......KKKK....KKKK......",
	},
	// Runner: mid-stride, a scarf streaming.
	"unit_runner": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..........KKKKK.........",
		".........KDDDDDK........",
		".........KKTKTKK........",
		".........KKKKKKKTTt.....",
		"........KKKKKKKK..Tt....",
		".......KDKKKKKKK....t...",
		"......KDKKKKKKKKK.......",
		".....KK.KKKKKKKK........",
		"........KKKKKKK.........",
		".......KKK..KKKK........",
		"......KKK.....KKK.......",
		".....KKK.......KKK......",
		"........................",
	},
	// Medic: a lit cross on the chest.
	"unit_medic": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..........KKKK..........",
		".........KDDDDK.........",
		".........KKKKKK.........",
		".........KTKKTK.........",
		".........KKKKKK.........",
		".......KKKKKKKKKK.......",
		"......KDKKKWWKKKKK......",
		"......KKKKWWWWKKKK......",
		"......KDKKKWWKKKKK......",
		"......KKKKKKKKKKKK......",
		".......KKKKKKKKKK.......",
		".......KKK....KKK.......",
		"......KKKK....KKKK......",
		"........................",
	},
	// Junkbot: a scrap box on treads with one eye.
	"unit_junkbot": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........T............",
		"...........K............",
		"...........K............",
		"........KKKKKKK.........",
		".......KDDDDDDDK........",
		".......KKKKKKKKK........",
		".......KKKTTTKKK........",
		".......KKKKKKKKK........",
		"......KKKKKKKKKKK.......",
		"......KDKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		".......K.K.K.K.K........",
		".......KKKKKKKKK........",
		"........................",
	},
	// VOLT, lancer: a lightning crest and a lance.
	"hero_volt": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........T............",
		"..........KTK...........",
		".........KKKKK..........",
		"........KDDDDDK.........",
		"........KKKKKKK.......T.",
		"........KTTKTTK......KTK",
		"........KKKKKKK.....KDK.",
		".......KKKKKKKKK...KDK..",
		"......KDKKKKKKKKK.KDK...",
		".....KDKKKKKKKKKKKDK....",
		".....KKKKKKKKKKKKKK.....",
		".....KKKKKKKKKKKKK......",
		"......KKKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		".......KKKKKKKKK........",
		".......KKK...KKK........",
		"......KKK.....KKK.......",
		".....KKKK.....KKKK......",
	},
	// KITE, spotter: a visor and a tall aerial.
	"hero_kite": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..................T.....",
		"..................K.....",
		".................KDK....",
		"..................K.....",
		"........KKKKKK....K.....",
		".......KDDDDDDK...K.....",
		".......KKKKKKKK...K.....",
		".......KTTTTTTK...K.....",
		".......KKKKKKKK..KK.....",
		"......KKKKKKKKKKKK......",
		".....KDKKKKKKKKKKK......",
		".....KKKKKKKKKKKK.......",
		".....KDKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKK........",
		"......KKKKKKKKKK........",
		"......KKK....KKK........",
		".....KKKK....KKKK.......",
	},
	// BRAM, warden: a slab of a shield with a lit panel.
	"hero_bram": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		".........KKKKKK.........",
		"........KDDDDDDK........",
		"........KKKKKKKK........",
		"........KKTKKTKK........",
		"........KKKKKKKK........",
		"......KKKKKKKKKKKK......",
		".....KDDKKKKKKKKKKK.....",
		"..KKKKKKKKDKKKKKKKKK....",
		"..KDDDDDDKKKKKKKKKKK....",
		"..KDKKKKDKKKKKKKKKKKK...",
		"..KDKTTKDKKKKKKKKKKKK...",
		"..KDKTTKDKKKKKKKKKKKK...",
		"..KDKKKKDKKKKKKKKKKKK...",
		"..KDKKKKDKKKKKKKKKKK....",
		"..KDDDDDDKKKKKKKKKKK....",
		"..KKKKKKKKKKKKKKKKKK....",
		"........KKKKK.KKKKK.....",
		".......KKKKKK.KKKKKK....",
	},
	// SABLE, infiltrator: crouched, a blade low.
	"hero_sable": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..........KKKK..........",
		".........KDDDDK.........",
		"........KKKKKKKK........",
		"........KTKKKKTK........",
		"........KKKKKKKK........",
		".........KKKKKK.........",
		".......KKKKKKKKKK.......",
		"......KDKKKKKKKKKK......",
		".....KDKKKKKKKKKKKKKK...",
		".....KKKKKKKKKKKK..KDK..",
		"......KKKKKKKKKK.....KD.",
		"......KKKKKKKKKK.......D",
		".......KKKKKKKK.........",
		".......KKKKKKKK.........",
		"......KKK....KKK........",
		".....KKK......KKK.......",
		"....KKK........KKK......",
	},
	// ORDO, bombard: a mortar tube over the shoulder.
	"hero_ordo": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...............KKK......",
		"..............KDDDK.....",
		".............KDKKK......",
		"............KDKKK.......",
		"...........KDKKK........",
		"..........KKKKK.........",
		".......KKKKKKK..........",
		"......KDDDDDDK..........",
		"......KKKKKKKK..........",
		"......KTTKKTTK..........",
		"......KKKKKKKK..........",
		"....KKKKKKKKKKKK........",
		"...KDKKKKKKKKKKKK.......",
		"...KKKKKKKKKKKKKK.......",
		"...KDKKKKKKKKKKKK.......",
		"...KKKKKKKKKKKKKK.......",
		"....KKKKKKKKKKKK........",
		"....KKKK....KKKK........",
		"...KKKKK....KKKKK.......",
	},
	// Drone (KITE): a quadcopter with one eye.
	"unit_drone": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...KDDDK........KDDDK...",
		".....K............K.....",
		".....KKKKKKKKKKKKKK.....",
		"......KKKKTTTTKKKK......",
		".......KKKKKKKKKK.......",
		"........K......K........",
		".......KK......KK.......",
		"........................",
		"........................",
		"......dddddddddddd......",
	},
}

// Poses are extra frames a figure strikes at a moment of the turn, by
// name. "attack" is shown when it attacks or casts. A figure without one
// lunges in its standing frame.
var Poses = map[string]map[string][]string{
	"hero_hask": {"attack": {
		"........................",
		"........................",
		"........................",
		".........K......K.......",
		"...KK....KK....KK...KK..",
		"...KDK....KKKKKK...KDK..",
		"...KKK...KDDDDDDK..KKK..",
		"....KK...KKKKKKKK..KK...",
		"....KK...KKTTKTTK..KK...",
		".....KK...KKKKKK..KK....",
		"......KKKKKKKKKKKKK.....",
		".....KKDDKKKKKKKKDDK....",
		"....KDDKKKKKKKKKKKKDK...",
		"....KDKKKKKKKKKKKKKKK...",
		"....KKKKKKKKKKKKKKKKK...",
		".....KKKKKKKdKKKKKKK....",
		".....KKKKKKKdKKKKKKK....",
		"......KKKKKKKKKKKKK.....",
		".......KKKKKKKKKKK......",
		".......KKKKKKKKKKK......",
		"........KKKKKKKKKK......",
		"........KKKKK.KKKK......",
		".......KKKKK..KKKKK.....",
		".......KKKK....KKKK.....",
	}},
	"hero_wren": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..........DD............",
		".........DKKD...........",
		"........DKKKKD..........",
		"......DDKKKKKKDD........",
		"....DDDDDDDDDDDDDD......",
		".......KKKKKKKK.........",
		".......KTTKKTTK.........",
		".......KKKKKKKKDDDDDDDD.",
		"......KKKKKKKKKKKKKKKKKT",
		".....KDKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		"....KDKKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKK........",
		"......KKK....KKK........",
		".....KKKK....KKKK.......",
	}},
	"hero_nul": {"attack": {
		"........................",
		"........................",
		"........................",
		"........T..T..T.........",
		"........K.KDK.K.........",
		"........KK.K.KK.........",
		".........KKKKK..........",
		".........KKKKK..........",
		"........KKKKKKK.........",
		".......KDKKKKKKK........",
		".......KKTKKKTKK........",
		".......KKKKKKKKK........",
		".....KKDKKKKKKKKKK......",
		"...KKDKKKKKKKKKKKKKK....",
		"..KDKKKKKKKTKKKKKKKKK...",
		".KDKKKKKKKKKKKKKKKKKKK..",
		".KKKKKKKKKKKKKKKKKKKKK..",
		"KKKK.KKKKKKKKKKKK.KKKKK.",
		"KK....KKKKKKKKKK....KKK.",
		"......KKK.KKK.KKK.......",
		"......K....K....K.......",
		"........................",
		"........................",
		"........dddddddd........",
	}},
	"hero_mott": {"attack": {
		"........................",
		"........................",
		"........................",
		".............tTTTTt.....",
		"............tTWWWWTt....",
		"............TWWWWWWT....",
		"............TWWWWWWT....",
		"............tTWWWWTt....",
		".............tTTTTt.....",
		"................KK......",
		"...............KK.......",
		".......KKKKKK.KK........",
		"......KDDDDDDKK.........",
		"......KKKKKKKKK.........",
		"......KKTKKTKKK.........",
		"....KKKKKKKKKKK.........",
		"...KKKKKKKKKKKKK........",
		"...KDKKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		"....KDKKKKKKKKKKK.......",
		"....KKKKKKKKKKKKK.......",
		".....KKKKKKKKKKK........",
		"......KKK...KKK.........",
		".....KKKK...KKKK........",
	}},
	"hero_tally": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"....................KKK.",
		"...................KDTDK",
		"...................KKKKK",
		"....................K.K.",
		"........................",
		".......KKKKK............",
		"......KDDDDDK...........",
		"......KTTKTTK...........",
		"......KKKKKKK...........",
		".......KKKKK............",
		".....KKKKKKKKK..........",
		"....KDKKKKKKKKKKKKKK....",
		"....KKKKKKKKKKKK........",
		"....KKKKKKKKKKKK........",
		"....KDKKKKKKKKKK........",
		".....KKKKKKKKKK.........",
		".....KKKKKKKKKK.........",
		"......KKK..KKK..........",
		".....KKKK..KKKK.........",
	}},
	"unit_lineman": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..................D.....",
		".................D.D....",
		".........DDDDDD.D...D...",
		"........DKKKKKKD.D.D....",
		".......DDDDDDDDDD.DK....",
		"........KKKKKKKK..KK....",
		"........KKTKKTKK.KK.....",
		"........KKKKKKKKKK......",
		".......KKKKKKKKKK.......",
		"......KDKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		"......KDKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		".......KKKKKKKKKK.......",
		".......KKK....KKK.......",
		"......KKKK....KKKK......",
	}},
	"unit_ranged": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........T............",
		"...........K............",
		".........KKKKKK.........",
		"........KDDDDDDK........",
		"........KKKKKKKK........",
		"........KTTTTTTK........",
		"........KKKKKKKK........",
		".......KKKKKKKKKK.......",
		"......KDKKKKKKKKKK....T.",
		"......KKKKKKKKKKKKKKKKTW",
		"......KDKKKKKKKKKKDDDDT.",
		"......KKKKKKKKKKKK......",
		".......KKKKKKKKKK.......",
		".......KKK....KKK.......",
		"......KKKK....KKKK......",
	}},
	"hero_volt": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........T............",
		"..........KTK...........",
		".........KKKKK..........",
		"........KDDDDDK.........",
		"........KKKKKKK.........",
		"........KTTKTTK.........",
		"........KKKKKKK.........",
		".......KKKKKKKKKKKKKKKTW",
		"......KDKKKKKKKKKKKKKDT.",
		".....KDKKKKKKKKKKK......",
		".....KKKKKKKKKKKKK......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		"......KKKKKKKKKKK.......",
		".......KKKKKKKKK........",
		".......KKK...KKK........",
		"......KKK.....KKK.......",
		".....KKKK.....KKKK......",
	}},
	"hero_kite": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		".....................T..",
		"....................TWT.",
		".....................K..",
		"....................K...",
		"........KKKKKK.....K....",
		".......KDDDDDDK...K.....",
		".......KKKKKKKK..K......",
		".......KTTTTTTK.K.......",
		".......KKKKKKKKK........",
		"......KKKKKKKKKK........",
		".....KDKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		".....KDKKKKKKKKKK.......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKK........",
		"......KKKKKKKKKK........",
		"......KKK....KKK........",
		".....KKKK....KKKK.......",
	}},
	"hero_bram": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"...........KKKKKK.......",
		"..........KDDDDDDK......",
		"..........KKKKKKKK......",
		"..........KKTKKTKK......",
		"..........KKKKKKKK......",
		"........KKKKKKKKKKKK....",
		".KKKKKKKKKKKKKKKKKKKK...",
		".KDDDDDDKKKKKKKKKKKKK...",
		".KDKKKKDKKKKKKKKKKKKKK..",
		".KDKTTKDKKKKKKKKKKKKKK..",
		".KDKTTKDKKKKKKKKKKKKKK..",
		".KDKKKKDKKKKKKKKKKKKKK..",
		".KDKKKKDKKKKKKKKKKKKK...",
		".KDDDDDDKKKKKKKKKKKKK...",
		".KKKKKKKKKKKKKKKKKKKK...",
		"..........KKKKK.KKKKK...",
		".........KKKKKK.KKKKKK..",
	}},
	"hero_sable": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..........KKKK..........",
		".........KDDDDK.........",
		"........KKKKKKKK........",
		"........KTKKKKTK........",
		"........KKKKKKKK........",
		".........KKKKKK.........",
		".......KKKKKKKKKKKKKKDDW",
		"......KDKKKKKKKKKKK.....",
		".....KDKKKKKKKKKKK......",
		".....KKKKKKKKKKKK.......",
		"......KKKKKKKKKK........",
		"......KKKKKKKKKK........",
		".......KKKKKKKK.........",
		"......KKKK..KKKK........",
		".....KKK......KKK.......",
		"....KKK........KKK......",
	}},
	"hero_ordo": {"attack": {
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"..............TWT.......",
		"...............KKK......",
		"..............KDDDK.....",
		".............KDKKK......",
		"............KDKKK.......",
		"...........KDKKK........",
		"..........KKKKK.........",
		".......KKKKKKK..........",
		"......KDDDDDDK..........",
		"......KKKKKKKK..........",
		"......KTTKKTTK..........",
		"......KKKKKKKK..........",
		"....KKKKKKKKKKKK........",
		"...KDKKKKKKKKKKKK.......",
		"...KKKKKKKKKKKKKK.......",
		"...KDKKKKKKKKKKKK.......",
		"...KKKKKKKKKKKKKK.......",
		"....KKKKKKKKKKKK........",
		"...KKKKK....KKKKK.......",
	}},
}
